/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CombosRouteImport } from './routes/combos'
import { Route as HelpRouteImport } from './routes/help'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as PolicyRouteImport } from './routes/policy'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiNotifyAdminRouteImport } from './routes/api/notify-admin'
import { Route as BrandBrandRouteImport } from './routes/brand.$brand'
import { Route as ComboIdRouteImport } from './routes/combo.$id'
import { Route as InvoiceIdRouteImport } from './routes/invoice.$id'
import { Route as OrderIdRouteImport } from './routes/order.$id'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CombosRoute = CombosRouteImport.update({
  id: '/combos',
  path: '/combos',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const PolicyRoute = PolicyRouteImport.update({
  id: '/policy',
  path: '/policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotifyAdminRoute = ApiNotifyAdminRouteImport.update({
  id: '/api/notify-admin',
  path: '/api/notify-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandBrandRoute = BrandBrandRouteImport.update({
  id: '/brand/$brand',
  path: '/brand/$brand',
  getParentRoute: () => rootRouteImport,
} as any)
const ComboIdRoute = ComboIdRouteImport.update({
  id: '/combo/$id',
  path: '/combo/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoiceIdRoute = InvoiceIdRouteImport.update({
  id: '/invoice/$id',
  path: '/invoice/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderIdRoute = OrderIdRouteImport.update({
  id: '/order/$id',
  path: '/order/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/checkout': typeof CheckoutRoute
  '/combos': typeof CombosRoute
  '/help': typeof HelpRoute
  '/orders': typeof OrdersRoute
  '/policy': typeof PolicyRoute
  '/products': typeof ProductsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/wishlist': typeof WishlistRoute
  '/api/chat': typeof ApiChatRoute
  '/api/notify-admin': typeof ApiNotifyAdminRoute
  '/brand/$brand': typeof BrandBrandRoute
  '/combo/$id': typeof ComboIdRoute
  '/invoice/$id': typeof InvoiceIdRoute
  '/order/$id': typeof OrderIdRoute
  '/product/$slug': typeof ProductSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/checkout': typeof CheckoutRoute
  '/combos': typeof CombosRoute
  '/help': typeof HelpRoute
  '/orders': typeof OrdersRoute
  '/policy': typeof PolicyRoute
  '/products': typeof ProductsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/wishlist': typeof WishlistRoute
  '/api/chat': typeof ApiChatRoute
  '/api/notify-admin': typeof ApiNotifyAdminRoute
  '/brand/$brand': typeof BrandBrandRoute
  '/combo/$id': typeof ComboIdRoute
  '/invoice/$id': typeof InvoiceIdRoute
  '/order/$id': typeof OrderIdRoute
  '/product/$slug': typeof ProductSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/checkout': typeof CheckoutRoute
  '/combos': typeof CombosRoute
  '/help': typeof HelpRoute
  '/orders': typeof OrdersRoute
  '/policy': typeof PolicyRoute
  '/products': typeof ProductsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/wishlist': typeof WishlistRoute
  '/api/chat': typeof ApiChatRoute
  '/api/notify-admin': typeof ApiNotifyAdminRoute
  '/brand/$brand': typeof BrandBrandRoute
  '/combo/$id': typeof ComboIdRoute
  '/invoice/$id': typeof InvoiceIdRoute
  '/order/$id': typeof OrderIdRoute
  '/product/$slug': typeof ProductSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/combos'
    | '/help'
    | '/orders'
    | '/policy'
    | '/products'
    | '/reset-password'
    | '/wishlist'
    | '/api/chat'
    | '/api/notify-admin'
    | '/brand/$brand'
    | '/combo/$id'
    | '/invoice/$id'
    | '/order/$id'
    | '/product/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/combos'
    | '/help'
    | '/orders'
    | '/policy'
    | '/products'
    | '/reset-password'
    | '/wishlist'
    | '/api/chat'
    | '/api/notify-admin'
    | '/brand/$brand'
    | '/combo/$id'
    | '/invoice/$id'
    | '/order/$id'
    | '/product/$slug'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/combos'
    | '/help'
    | '/orders'
    | '/policy'
    | '/products'
    | '/reset-password'
    | '/wishlist'
    | '/api/chat'
    | '/api/notify-admin'
    | '/brand/$brand'
    | '/combo/$id'
    | '/invoice/$id'
    | '/order/$id'
    | '/product/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  CartRoute: typeof CartRoute
  CategoriesRoute: typeof CategoriesRoute
  CheckoutRoute: typeof CheckoutRoute
  CombosRoute: typeof CombosRoute
  HelpRoute: typeof HelpRoute
  OrdersRoute: typeof OrdersRoute
  PolicyRoute: typeof PolicyRoute
  ProductsRoute: typeof ProductsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  WishlistRoute: typeof WishlistRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiNotifyAdminRoute: typeof ApiNotifyAdminRoute
  BrandBrandRoute: typeof BrandBrandRoute
  ComboIdRoute: typeof ComboIdRoute
  InvoiceIdRoute: typeof InvoiceIdRoute
  OrderIdRoute: typeof OrderIdRoute
  ProductSlugRoute: typeof ProductSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/combos': {
      id: '/combos'
      path: '/combos'
      fullPath: '/combos'
      preLoaderRoute: typeof CombosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policy': {
      id: '/policy'
      path: '/policy'
      fullPath: '/policy'
      preLoaderRoute: typeof PolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notify-admin': {
      id: '/api/notify-admin'
      path: '/api/notify-admin'
      fullPath: '/api/notify-admin'
      preLoaderRoute: typeof ApiNotifyAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand/$brand': {
      id: '/brand/$brand'
      path: '/brand/$brand'
      fullPath: '/brand/$brand'
      preLoaderRoute: typeof BrandBrandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/combo/$id': {
      id: '/combo/$id'
      path: '/combo/$id'
      fullPath: '/combo/$id'
      preLoaderRoute: typeof ComboIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoice/$id': {
      id: '/invoice/$id'
      path: '/invoice/$id'
      fullPath: '/invoice/$id'
      preLoaderRoute: typeof InvoiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/$id': {
      id: '/order/$id'
      path: '/order/$id'
      fullPath: '/order/$id'
      preLoaderRoute: typeof OrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  CartRoute: CartRoute,
  CategoriesRoute: CategoriesRoute,
  CheckoutRoute: CheckoutRoute,
  CombosRoute: CombosRoute,
  HelpRoute: HelpRoute,
  OrdersRoute: OrdersRoute,
  PolicyRoute: PolicyRoute,
  ProductsRoute: ProductsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  WishlistRoute: WishlistRoute,
  ApiChatRoute: ApiChatRoute,
  ApiNotifyAdminRoute: ApiNotifyAdminRoute,
  BrandBrandRoute: BrandBrandRoute,
  ComboIdRoute: ComboIdRoute,
  InvoiceIdRoute: InvoiceIdRoute,
  OrderIdRoute: OrderIdRoute,
  ProductSlugRoute: ProductSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
